import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  vtsTerminalSidebar: [{type: 'autogenerated', dirName: '.'}],
  psdLayerAnimationSidebar: [{type: 'autogenerated', dirName: '.'}],
  live2dPhysicsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
